name: Assign Project and Member
on:
  issues:
    types:
      - opened
jobs:
  label_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - run: |
          gh issue edit "$NUMBER" --add-project "$PROJECT" --add-label "$LABELS"
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          LABELS: ${{ secrets.REPO_TEAM }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          PROJECT: ${{ secrets.ASSIGN_PROJECT }}
